name: Manual Checklist Sync

# Quick manual trigger for immediate checklist updates from Azure/review-checklists
# Use this when you need to sync checklists outside the monthly schedule

on:
  workflow_dispatch:
    inputs:
      checklist_types:
        description: 'Specific checklist types to sync (comma-separated, e.g., aks,appsvc,security). Leave empty for all.'
        required: false
        default: ''
        type: string
      preserve_custom_ai:
        description: 'Preserve custom AI Landing Zone checklist'
        required: false
        default: true
        type: boolean
      create_backup:
        description: 'Create backup of existing checklists'
        required: false
        default: true
        type: boolean

jobs:
  manual-sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger checklist update
        uses: actions/github-script@v7
        with:
          script: |
            // Trigger the checklist update workflow directly
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'update-checklists.yml',
              ref: 'main',
              inputs: {
                checklist_types: '${{ inputs.checklist_types }}',
                preserve_custom_ai: '${{ inputs.preserve_custom_ai }}',
                create_backup: '${{ inputs.create_backup }}'
              }
            });
            console.log('✅ Triggered checklist update workflow');

      - name: Manual sync summary
        run: |
          echo "🚀 Manual checklist sync initiated!"
          echo "📅 Triggered at: $(date)"
          echo ""
          echo "Options selected:"
          echo "- Checklist types: ${{ inputs.checklist_types || 'all' }}"
          echo "- Preserve custom AI: ${{ inputs.preserve_custom_ai }}"
          echo "- Create backup: ${{ inputs.create_backup }}"
          echo ""
          echo "📋 Syncing directly from Azure/review-checklists repository"
          echo "Check the Actions tab for progress updates."